### ISSUE TITLE
Gem won't run.  Not even with `-h` option

### ISSUE THREAD

**Issue by bhollan** [flyerhzm/rails_best_practices#346]
`gem install rails_best_practices` went fine.  I even tried installing old releases.

I've tried installing via command line and Gemfile, but any time I invoke the gem, I get the same result:
```
/home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:208:in `require': /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/lib/rails_best_practices/core/check.rb:276: unknown type of %string (SyntaxError)
                if %i[symbol_literal string_literal...
                      ^
/home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/lib/rails_best_practices/core/check.rb:276: syntax error, unexpected $end
                if %i[symbol_literal string_literal...
                      ^
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:208:in `__require'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:98:in `block in require_all'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/lib/rails_best_practices/core.rb:3:in `<top (required)>'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/lib/rails_best_practices.rb:5:in `require'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/lib/rails_best_practices.rb:5:in `<top (required)>'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/bin/rails_best_practices:6:in `require'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/gems/rails_best_practices-1.19.4/bin/rails_best_practices:6:in `<top (required)>'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/bin/rails_best_practices:23:in `load'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/bin/rails_best_practices:23:in `<main>'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:24:in `eval'
        from /home/brianh/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:24:in `<main>'
```

I know I'm running an old version of Ruby, but I just joined a new team and this is all part of cleaning up and modernizing.

**Comment by bhollan** [comment]
If I do `rvm use 2.6.0`, it runs, but I'd rather run it with the "real" Ruby version I'm using engaged.

**Comment by flyerhzm** [comment]
@bhollan sorry but rails_best_practices doesn't support ruby 1.9.3 anymore.

**Comment by mjobin-mdsol** [comment]
ruby 1.9.3 ? in 2019 ? wow
